[options]
admin_passwd = 9vyf-dcwb-bmp6
db_host = db
db_port = 5432
db_user = odoo
db_password = AJ9IkOp2ZsiOVNDzGqWE01Wh
db_name = elgordo
addons_path = /mnt/extra-addons,/mnt/custom-addons
proxy_mode = True
list_db = True
without_demo = True
http_enable = True
max_cron_threads = 1
workers = 4
limit_memory_hard = 1073741824
limit_memory_soft = 751619276
limit_request = 8192
limit_time_cpu = 60
limit_time_real = 120