# -*- coding: utf-8 -*-
"""Thermal receipt logo printer for Pizzeria El Gordo.

Pre-built ESC/POS bytes cached in memory — loaded once at module import,
never re-read from disk. File generated by scripts/process_logo.py.
"""

import logging
import subprocess

from odoo import models

_logger = logging.getLogger(__name__)

LOGO_ESC = "/images/pizzeria_logo.escpos"
LOGO_RAW = "/images/pizzeria_logo_raw.escpos"

_cached_logo_esc = None
_cached_logo_raw = None


def _load_logo(path):
    try:
        with open(path, "rb") as f:
            return f.read()
    except IOError as e:
        _logger.error("Failed to read logo file %s: %s", path, e)
        return None


def _get_logo_esc():
    global _cached_logo_esc
    if _cached_logo_esc is None:
        _cached_logo_esc = _load_logo(LOGO_ESC)
    return _cached_logo_esc


def _get_logo_raw():
    global _cached_logo_raw
    if _cached_logo_raw is None:
        _cached_logo_raw = _load_logo(LOGO_RAW)
    return _cached_logo_raw


class ReceiptLogo(models.AbstractModel):
    _name = "receipt.logo"
    _description = "Thermal receipt logo printer"

    def print_logo(self, printer="XP-80"):
        data = _get_logo_esc()
        if data is None:
            return False
        try:
            result = subprocess.run(
                ["lp", "-d", printer, "-o", "raw"],
                input=data,
                capture_output=True,
                timeout=10,
            )
            if result.returncode != 0:
                _logger.error("Logo print failed: %s", result.stderr.decode(errors="replace"))
                return False
            _logger.info("Logo printed to %s", printer)
            return True
        except FileNotFoundError:
            _logger.error("CUPS lp command not found on this server")
            return False
        except Exception as e:
            _logger.error("Logo print error: %s", e)
            return False

    @staticmethod
    def print_logo_static(printer="XP-80"):
        data = _get_logo_esc()
        if data is None:
            return False
        try:
            result = subprocess.run(
                ["lp", "-d", printer, "-o", "raw"],
                input=data,
                capture_output=True,
                timeout=10,
            )
            if result.returncode != 0:
                _logger.error("Logo print failed: %s", result.stderr.decode(errors="replace"))
                return False
            _logger.info("Logo printed to %s", printer)
            return True
        except FileNotFoundError:
            _logger.error("CUPS lp command not found on this server")
            return False
        except Exception as e:
            _logger.error("Logo print error: %s", e)
            return False

    @staticmethod
    def get_logo_escpos_bytes():
        data = _get_logo_raw()
        if data is None:
            raise IOError("Logo file not available: %s" % LOGO_RAW)
        return data